name: Eco Evolution
favicon: null
layout_spectrum: 0.601844432996586
typography_spectrum: 0.3734090852085501
title: Hydro Specialists
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.5284012039192021
  lightness: 0.09353908849880099
  saturation: 0.6062576884869486
  rhythmicContrast: 0.6582118128426373
purpose: []
